services:
  busylight_manager:
    build:
      context: .
      dockerfile: src/busylight_manager/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host
    # The container needs to be privileged to access the USB device.
    #
    # Note: Just mapping the device /dev/hidraw4 inside the container does not work properly.
    privileged: true

  experiment_performer:
    build:
      context: .
      dockerfile: src/experiment_performer/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: host

  pedal_listener:
    build:
      context: .
      dockerfile: src/pedal_listener/Dockerfile
    # The container needs to be privileged so that /dev devices (namely, the USB pedal) are created.
    privileged: true
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host
  
  remote_controller:
    build:
      context: .
      dockerfile: src/remote_controller/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host

  stimulation_allower:
    build:
      context: .
      dockerfile: src/stimulation_allower/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: host

  targeting:
    build:
      context: .
      dockerfile: src/targeting/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: host

  trial_logger:
    build:
      context: .
      dockerfile: src/trial_logger/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - MTMS_EXPERIMENT_LOGS_DIR=/app/mtms_experiment_logs
    volumes:
      - '$MTMS_EXPERIMENT_LOGS_DIR:/app/mtms_experiment_logs'
    network_mode: host

  trial_performer:
    build:
      context: .
      dockerfile: src/trial_performer/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: host

  trial_validator:
    build:
      context: .
      dockerfile: src/trial_validator/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: host

  voltage_setter:
    build:
      context: .
      dockerfile: src/voltage_setter/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: host

  waveform_utils:
    build:
      context: .
      dockerfile: src/waveform_utils/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host

  waveform_approximator:
    build:
      context: .
      dockerfile: src/waveform_approximator/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    volumes:
      # Mount the whole MATLAB installation into the container; this is needed for the container
      # to be able to find MATLAB license (located in /usr/local/MATLAB/[version]/licenses/).
      #
      # A better solution would be to mount only the license file, but the MATLAB version is defined
      # site-specific .env file (e.g., sites/aalto/.env), which is not easily available for
      # docker-compose.yml, but only for Dockerfile.
      - '/usr/local/MATLAB:/usr/local/MATLAB'
    network_mode: host

  # MEP-related services
  eeg_bridge:
    build:
      context: .
      dockerfile: src/eeg_bridge/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - EEG_PORT=50001
      - EEG_DEVICE=neurone
    # The container needs to be privileged to set real-time priority.
    privileged: true
    network_mode: host

  timebase_calibrator:
    build:
      context: .
      dockerfile: src/timebase_calibrator/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host

  # eeg_gatherer:
  #   build:
  #     context: .
  #     dockerfile: src/eeg_gatherer/Dockerfile
  #   env_file:
  #     - ${MTMS_ENV_FILE}
  #   environment:
  #     - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
  #   # The container needs to be privileged to set real-time priority.
  #   privileged: true
  #   network_mode: host

  mep_analyzer:
    build:
      context: .
      dockerfile: src/mep_analyzer/Dockerfile
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host

  rosbridge:
    build:
      context: .
      dockerfile: src/rosbridge/Dockerfile
      args:
        INTERFACES_PATH: interfaces
    env_file:
      - ${MTMS_ENV_FILE}
    environment:
      - ROSBRIDGE_PORT=9091
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
    network_mode: host
