/** Heartbeats the UI treats as required; all use std_msgs/msg/Empty. */
export const REQUIRED_MTMS_HEARTBEATS = [
  { id: 'busylight_manager', topic: '/mtms/busylight_manager/heartbeat', label: 'busylight_manager' },
  { id: 'experiment_performer', topic: '/mtms/experiment_performer/heartbeat', label: 'experiment_performer' },
  { id: 'pedal_listener', topic: '/mtms/pedal_listener/heartbeat', label: 'pedal_listener' },
  { id: 'trial_logger', topic: '/mtms/trial_logger/heartbeat', label: 'trial_logger' },
  { id: 'voltage_setter', topic: '/mtms/voltage_setter/heartbeat', label: 'voltage_setter' },
  { id: 'waveform_approximator', topic: '/mtms/waveform_approximator/heartbeat', label: 'waveform_approximator' },
  { id: 'get_default_waveform', topic: '/mtms/waveform_utils/get_default_waveform/heartbeat', label: 'get_default_waveform' },
  { id: 'get_multipulse_waveforms', topic: '/mtms/waveform_utils/get_multipulse_waveforms/heartbeat', label: 'get_multipulse_waveforms' },
  { id: 'reverse_polarity', topic: '/mtms/waveform_utils/reverse_polarity/heartbeat', label: 'reverse_polarity' },
  { id: 'mtms_device', topic: '/mtms/device/heartbeat', label: 'mtms_device' },
  { id: 'eeg_bridge', topic: '/mtms/eeg_bridge/heartbeat', label: 'eeg_bridge' },
  { id: 'trigger_processor', topic: '/mtms/trigger_processor/heartbeat', label: 'trigger_processor' },
  { id: 'remote_controller', topic: '/mtms/remote_controller/heartbeat', label: 'remote_controller' },
  { id: 'targeting', topic: '/mtms/targeting/heartbeat', label: 'targeting' },
  { id: 'stimulation_allower', topic: '/mtms/stimulation_allower/heartbeat', label: 'stimulation_allower' },
  { id: 'timebase_calibrator', topic: '/mtms/timebase_calibrator/heartbeat', label: 'timebase_calibrator' },
  { id: 'trial_performer', topic: '/mtms/trial_performer/heartbeat', label: 'trial_performer' },
] as const
