# Request events from the mTMS device.
#
# Response: Boolean indicating if requesting was successful.

mtms_event_interfaces/Pulse[] pulses
mtms_event_interfaces/Charge[] charges
mtms_event_interfaces/Discharge[] discharges
mtms_event_interfaces/TriggerOut[] trigger_outs
---
bool success
