uint8 emg_channel

float64 mep_time_window_start
float64 mep_time_window_end

bool preactivation_check_enabled
float64 preactivation_check_time_window_start
float64 preactivation_check_time_window_end
float64 preactivation_check_voltage_range_limit

---
float64 amplitude
float64 latency
float64[] emg_buffer

# Status codes
uint8 NO_ERROR=0
uint8 PREACTIVATION_FAILED=1
uint8 LATE=2
uint8 TIMEOUT=3
uint8 SAMPLES_DROPPED=4
uint8 INVALID_EMG_CHANNEL=5

uint8 status
