float64 window_start
float64 window_end
---
float64[] eeg_buffer
float64[] emg_buffer

uint32 sampling_frequency

uint32 trigger_index

# Status codes
uint8 NO_ERROR=0
uint8 LATE=1
uint8 TIMEOUT=2
uint8 SAMPLES_DROPPED=3

uint8 status
