# ====================================================
# Targets
# ====================================================
mtms_targeting_interfaces/ElectricTarget[] targets

# ====================================================
# Timing
# ====================================================
float64 start_time
float64[] pulse_times_since_trial_start

# ====================================================
# Triggers
# ====================================================
bool[] trigger_enabled
float64[] trigger_delay

# ====================================================
# Configuration
# ====================================================
bool use_pulse_width_modulation_approximation
