# ROS service for estimating the capacitor voltage after giving a pulse using the given waveform.

uint16 voltage_before
mtms_waveform_interfaces/Waveform waveform
uint8 coil_number
---
bool success
uint16 voltage_after
